name: CI

on:
  push:
    branches:[main]
  pull_request:
    branches:[main]

jobs:
  build-and-test:
    run-on: ubuntu-latest

    steps:
      - name: venCheckout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Train model
        run: python app/model.py

      - name: Testhealth endpoint
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 3
          curl -f http://localhost:8000/health

      - name: Build Docker image
        run: docker build -t burnout-predictor .

      - name: Test Docker container
        run: |
          docker run -d -p 8000:8000 --name test-container burnout-predictor
          sleep 5
          curl -f http://localhost:8000/health
          docker stop test-container